### ISSUE TITLE
ch09 - breaking in trimToRegion when featurizing S&P-crudeoil-etc factors

### ISSUE THREAD

**Issue by jamiis** [sryza/aas#51]
It's breaking when calling `trimmed.head._1` in `trimToRegion` from line 200 in `featurize()`. I'm still relatively new to scala so I'm not well equipped to investigate what exactly is breaking. I tried only running it on `factors1` and also only on `factors2` instead of the two concatenated together, and it still breaks both times. `factors2` consists of the S&P and NASDAQ data downloaded with the provided shell script -- as opposed to crude oil and us t-bonds copy-and-pasted from investing.com -- so I'm thinking this might be a true bug rather than something I introduced. I'll go hone my scala skills a bit more so I can investigate this further. If I find anything I'll let you know.

`spark-submit --class com.cloudera.datascience.risk.RunRisk --master local target/ch09-risk-1.0.2-jar-with-dependencies.jar`

```
Exception in thread "main" java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
        at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
        at scala.collection.IterableLike$class.head(IterableLike.scala:91)
        at scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:108)
        at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
        at scala.collection.mutable.ArrayOps$ofRef.head(ArrayOps.scala:108)
        at com.cloudera.datascience.risk.RunRisk$.trimToRegion(RunRisk.scala:200)
        at com.cloudera.datascience.risk.RunRisk$$anonfun$16.apply(RunRisk.scala:112)
        at com.cloudera.datascience.risk.RunRisk$$anonfun$16.apply(RunRisk.scala:112)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
        at com.cloudera.datascience.risk.RunRisk$.readStocksAndFactors(RunRisk.scala:112)
        at com.cloudera.datascience.risk.RunRisk$.main(RunRisk.scala:34)
        at com.cloudera.datascience.risk.RunRisk.main(RunRisk.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by srowen** [comment]
@sryza is it sufficient to return an empty result from `trimToRegion` when the region contains nothing? or does it always need to contain at least the start, end tuples?

**Comment by sryza** [comment]
Hi @jamiis, are you able to check whether there are non-NaN values in the data that's being passed to `trimToRegion`?

**Comment by srowen** [comment]
@sryza do you mean NaNs? either way is it possible to change things to proactively reject these or else do something sensible in that case?

**Comment by sryza** [comment]
@srowen I mean non-NaNs.  My worry is that the dataset is 100% NaNs, which implies some sort of problem upstream, and can't really be handled in current part of the code being discussed.

**Comment by appleyuchi** [comment]
I can not really follow you, @sryza @sryza 
could you tell me if this problem is solved?
I have the same problem ,how can I work around it?
Thanks in advance!

**Comment by appleyuchi** [comment]
Exception in thread "main" java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
	at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)
	at scala.collection.IterableLike$class.head(IterableLike.scala:107)
	at scala.collection.mutable.ArrayOps$ofDouble.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:270)
	at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:126)
	at scala.collection.mutable.ArrayOps$ofDouble.head(ArrayOps.scala:270)
	at RunRisk.fivePercentVaR(RunRisk.scala:301)
	at RunRisk$.main(RunRisk.scala:62)
	at RunRisk.main(RunRisk.scala)

**Comment by appleyuchi** [comment]
The 62th line is:
   val valueAtRisk = runRisk.fivePercentVaR(trials)
