### ISSUE TITLE
chap2 runtime error

### ISSUE THREAD

**Issue by Patrick2611** [sryza/aas#70]
Exception in thread "main" java.lang.NoClassDefFoundError: org/spark-project/guava/util/concurrent/ThreadFactoryBuilder
	at org.apache.spark.util.Utils$.<init>(Utils.scala:858)
	at org.apache.spark.util.Utils$.<clinit>(Utils.scala)
	at org.apache.spark.SparkConf.<init>(SparkConf.scala:58)
	at org.apache.spark.SparkConf.<init>(SparkConf.scala:52)
	at org.test.spark.HelloWorld$.main(HelloWorld.scala:15)
	at org.test.spark.HelloWorld.main(HelloWorld.scala)
Caused by: java.lang.ClassNotFoundException: org.spark-project.guava.util.concurrent.ThreadFactoryBuilder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 6 more
Exception in thread "delete Spark temp dirs" java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.util.Utils$
	at org.apache.spark.util.Utils$$anon$4.run(Utils.scala:177)

**Comment by srowen** [comment]
That typically means some problem with how you're deploying the app you built here, or how you built or deployed Spark. Spark is missing some of its dependencies at runtime. You'd have to describe how you are building and running the code here, and if applicable, building and running Spark.
