### ISSUE TITLE
the problem of ch08-geotime

### ISSUE THREAD

**Issue by zhishui06** [sryza/aas#93]
hello!
 I'm very interested in the cntent of ch08-geotime, so,I bulid your code in intellij idea(hadoop:2.7.3 spark:2.0.2 java:1.8.0_65 scala:2.11.8),then I submit the package of jar into spark,the error occur,I tried a lot of ways, but the problem is still not resolved.so I hope you can help me.thank you.the detail error as follows.
Exception in thread "main" java.lang.NoClassDefFoundError: spray/json/JsonReader
	at cn.edu.tju.geotime.RunGeoTime.main(RunGeoTime.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: spray.json.JsonReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

       how can i do?

**Comment by srowen** [comment]
It usually means you did not build an assembly jar with all dependencies. Spark apps need to ship whatever they use. The example code here does create assemblies.

**Comment by zhishui06** [comment]
The problem is solved,thank you very much.
